if(EXISTS "/home/lamiae/Downloads/transpiler-main/build3/antlr4cpp-prefix/src/antlr4cpp-build/runtime/antlr4_tests[1]_tests.cmake")
  include("/home/lamiae/Downloads/transpiler-main/build3/antlr4cpp-prefix/src/antlr4cpp-build/runtime/antlr4_tests[1]_tests.cmake")
else()
  add_test(antlr4_tests_NOT_BUILT antlr4_tests_NOT_BUILT)
endif()
